language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
        - php: 7.0

before_script:
    - composer selfupdate
    - composer update $COMPOSER_FLAGS

script: bin/test.sh
