language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
    include:
        - php: 5.3.3
          env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: hhvm
    - php: 7.0

before_script:
  - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
  - composer selfupdate
  - composer update $COMPOSER_FLAGS

script: bin/tester.sh
